"""Added total questions to score

Revision ID: efe9471a5ae3
Revises: 4567788bb92d
Create Date: 2025-01-09 15:43:13.202694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe9471a5ae3'
down_revision = '4567788bb92d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_questions', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_column('total_questions')

    # ### end Alembic commands ###
