"""Added total question to Score table

Revision ID: f212699c5acc
Revises: f7e7d9226e4d
Create Date: 2025-01-09 14:41:11.166502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f212699c5acc'
down_revision = 'f7e7d9226e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('categories_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['parent_id'], ['id'])

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_constraint('scores_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])

    with op.batch_alter_table('user_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_questions', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_answers', schema=None) as batch_op:
        batch_op.drop_column('total_questions')

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('scores_ibfk_2', 'categories', ['category_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('categories_ibfk_1', 'categories', ['parent_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
