"""Polishing my tables for deletion and good relationship

Revision ID: f7e7d9226e4d
Revises: 98a09a0e4497
Create Date: 2024-12-24 07:10:56.595948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7e7d9226e4d'
down_revision = '98a09a0e4497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_parent_id'), ['parent_id'], unique=False)
        batch_op.drop_constraint('categories_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['parent_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('category_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_id', sa.Integer(), nullable=False))
        batch_op.alter_column('category_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_category_questions_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_questions_question_id'), ['question_id'], unique=False)
        batch_op.drop_constraint('category_questions_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('category_questions_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'questions', ['question_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('questions_id')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trait', sa.String(length=50), nullable=False))
        batch_op.create_index(batch_op.f('ix_comments_threshold'), ['threshold'], unique=False)

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('category_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_scores_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint('scores_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('scores_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_answers', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('question_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_answer',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_user_answers_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_answers_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint('user_answers_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('user_answers_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'questions', ['question_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_comment', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('comment_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_user_comment_comment_id'), ['comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_comment_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint('user_comment_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('user_comment_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'comments', ['comment_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_comment_ibfk_1', 'comments', ['comment_id'], ['id'])
        batch_op.create_foreign_key('user_comment_ibfk_2', 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_user_comment_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_comment_comment_id'))
        batch_op.alter_column('comment_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user_answers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_answers_ibfk_2', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('user_answers_ibfk_1', 'questions', ['question_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_user_answers_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_answers_question_id'))
        batch_op.alter_column('user_answer',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('question_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('scores_ibfk_2', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('scores_ibfk_1', 'categories', ['category_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_scores_user_id'))
        batch_op.drop_index(batch_op.f('ix_scores_category_id'))
        batch_op.alter_column('category_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_threshold'))
        batch_op.drop_column('trait')

    with op.batch_alter_table('category_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('questions_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('category_questions_ibfk_2', 'questions', ['questions_id'], ['id'])
        batch_op.create_foreign_key('category_questions_ibfk_1', 'categories', ['category_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_category_questions_question_id'))
        batch_op.drop_index(batch_op.f('ix_category_questions_category_id'))
        batch_op.alter_column('category_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('question_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('categories_ibfk_1', 'categories', ['parent_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_categories_parent_id'))

    # ### end Alembic commands ###
